aws_region          = "ap-south-1"
environment         = "dev"
cluster_name        = "shopnow-app-eks"
management_key_name = "shopnow-key-pair"
allowed_ssh_cidr    = "0.0.0.0/0"
ecr_repo_prefix     = "shopnow-dev"
vpc_cidr            = "10.20.0.0/16"
public_subnet_cidrs = ["10.20.1.0/24", "10.20.2.0/24"]
instance_type       = "t2.small"
node_instance_types = ["t2.small"]  # Free Tier eligible instance type for EKS nodes
