apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: shopnow-ns
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: shopuser
  MONGO_INITDB_ROOT_PASSWORD: ShopNowPass123
  MONGODB_URI: mongodb://shopuser:ShopNowPass123@mongo:27017/shopnow?authSource=admin
