apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongo-secret
  namespace: shopnow-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: mongo-secret
    creationPolicy: Owner
  data:
  - secretKey: MONGO_INITDB_ROOT_USERNAME
    remoteRef:
      key: shopnow/mongo
      property: MONGO_INITDB_ROOT_USERNAME
  - secretKey: MONGO_INITDB_ROOT_PASSWORD
    remoteRef:
      key: shopnow/mongo
      property: MONGO_INITDB_ROOT_PASSWORD
  - secretKey: MONGODB_URI
    remoteRef:
      key: shopnow/mongo
      property: MONGODB_URI
